### ISSUE TITLE
sleek not building anymore (RequestError: getaddrinfo EAI_AGAIN github.com)

### ISSUE THREAD

**Issue by ransome1** [flathub/com.github.ransome1.sleek#2]
Hi there.

I can't get sleek to successfully build anymore. It seems the building machine either can't get DNS info for Github or something is wrong with the sources again. I needed to update the generated-sources.json due to updates on the package-lock.json.  But I didn't change the way I'm building it. Still doing it like this: `./flatpak-node-generator.py npm --xdg-layout package-lock.json`

@barthalion, could you maybe take a look at it if you have some time to spare?

This is the failed build: https://flathub.org/builds/#/builders/32/builds/39282

> electron@11.2.3 postinstall /run/build/sleek/sleek/node_modules/electron
> node install.js
RequestError: getaddrinfo EAI_AGAIN github.com
    at ClientRequest.<anonymous> (/run/build/sleek/sleek/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/run/build/sleek/sleek/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@11.2.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@11.2.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/sleek/flatpak-node/npm-cache/_logs/2021-02-14T08_03_08_391Z-debug.log
]2;flatpak-builder: Cleanup sleekError: module sleek: Child process exited with code 1
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64-2/build/.flatpak-builder/rofiles/rofiles-uGTR3a
program finished with exit code 1
elapsedTime=22.981732

**Comment by barthalion** [comment]
This should be fixed now.

**Comment by ransome1** [comment]
I can confirm it works again. Like magic ;)

**Comment by ransome1** [comment]
@barthalion I'm afraid I'm having the same issue again. Flathub sometimes is really a mystery to me. I have no idea what's going on and I can't really work with the error message in build log. Like usually something is going on with the offline mode.

Can you please help me out again?

Here is a the build that is failing: https://flathub.org/builds/#/builders/32/builds/75377
