### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by hfiguiere** [flathub/com.github.ransome1.sleek#58]
The last commit breaks the build (it's staled as I write this, but this is definitely a failure):

https://buildbot.flathub.org/#/builders/10/builds/11516

Apparently the new build process tries to download sonething off the internet.

**Comment by ransome1** [comment]
@hfiguiere thanks for pointing it out. But as with every Flathub build everythimng new breaks :/ I'll figure it out.

**Comment by ransome1** [comment]
@barthalion my builds fail over and over again and it's always related to some mysterious issues with the offline packages. I don't know how to solve this. Could you please take a look at it and tell me what's going wrong?

https://buildbot.flathub.org/#/builders/20/builds/8843

**Comment by ransome1** [comment]
Got it working.
